/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMotoristaRouteImport } from './routes/_app/motorista'
import { Route as AppEmpresaRouteImport } from './routes/_app/empresa'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppAdminRouteImport } from './routes/_app/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMotoristaRoute = AppMotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/empresa': typeof AppEmpresaRoute
  '/motorista': typeof AppMotoristaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/empresa': typeof AppEmpresaRoute
  '/motorista': typeof AppMotoristaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/empresa': typeof AppEmpresaRoute
  '/_app/motorista': typeof AppMotoristaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/configuracoes'
    | '/empresa'
    | '/motorista'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/admin' | '/configuracoes' | '/empresa' | '/motorista'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/configuracoes'
    | '/_app/empresa'
    | '/_app/motorista'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/motorista': {
      id: '/_app/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof AppMotoristaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/empresa': {
      id: '/_app/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppMotoristaRoute: typeof AppMotoristaRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEmpresaRoute: AppEmpresaRoute,
  AppMotoristaRoute: AppMotoristaRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
